
exclude:
  - languages

mapping:
  "David Molineus <david.molineus@netzmacht.de>":
    - "David Molineus <david.molineus@netzmacht.de>"
    - "David Molineus <mail@netzmacht.de>"

  "Alexander Kehr <info@kehr-solutions.de>":
    - "Alexander Kehr <info@kehr-solutions.de>"
