services:
  _defaults:
    public: true

  contao_bootstrap.core.config_subscriber:
    class: ContaoBootstrap\Core\Listener\ConfigSubscriber
    arguments:
      - '@contao_bootstrap.config'
    tags:
      - name: kernel.event_listener
        event: 'ContaoBootstrap\Core\Message\Command\InitializeEnvironment'
        method: 'enterApplicationContext'
      - name: kernel.event_listener
        event: 'ContaoBootstrap\Core\Message\Command\InitializeLayout'
        method: 'enterThemeContext'
      - name: kernel.event_listener
        event: 'ContaoBootstrap\Core\Message\Command\BuildContextConfig'
        method: 'buildContextConfig'

  contao_bootstrap.core.listener.parse_template:
    class: ContaoBootstrap\Core\Listener\TemplateParseListener
    arguments:
      - '@contao_bootstrap.view.template.pre_render_filter'
      - '@contao_bootstrap.view.template.post_render_filter'

  contao_bootstrap.core.listener.hook_listener:
    class: ContaoBootstrap\Core\Listener\HookListener
    arguments:
      - '@event_dispatcher'
      - '@contao_bootstrap.environment'

  contao_bootstrap.core.listener.layout_dca:
    class: ContaoBootstrap\Core\Listener\Dca\LayoutDcaListener
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@contao_bootstrap.environment'
      - '@netzmacht.contao_toolkit.contao.input_adapter'
      - '@netzmacht.contao_toolkit.repository_manager'

  contao_bootstrap.core.listener.module_dca:
    class: ContaoBootstrap\Core\Listener\Dca\ModuleDcaListener
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@translator'
      - '@database_connection'
      - '@contao.framework'
      - '@router'
      - '@netzmacht.contao_toolkit.contao.input_adapter'

  ContaoBootstrap\Core\Listener\BackendListener:
    arguments:
      - '@netzmacht.contao_toolkit.assets_manager'
      - '@netzmacht.contao_toolkit.routing.scope_matcher'
      - '%contao_bootstrap.backend.css%'
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.request' }
