services:
  contao_bootstrap.environment:
    class: ContaoBootstrap\Core\Environment
    public: true
    arguments:
      - '@event_dispatcher'

  contao_bootstrap.config:
    class: ContaoBootstrap\Core\Config\ArrayConfig
    arguments:
      - '%contao_bootstrap.config%'

  contao_bootstrap.view.template.pre_render_filter:
    class: ContaoBootstrap\Core\View\Template\Filter\TemplatePreRenderFilter
    arguments:
      - !tagged_iterator 'contao_bootstrap.pre_render_filter'

  contao_bootstrap.view.template.post_render_filter:
    class: ContaoBootstrap\Core\View\Template\Filter\TemplatePostRenderFilter
    arguments:
      - !tagged_iterator 'contao_bootstrap.post_render_filter'

  contao_bootstrap.core.helper.color_rotate:
    class: ContaoBootstrap\Core\Helper\ColorRotate

  contao_bootstrap.core.view.twig_extension:
    class: ContaoBootstrap\Core\View\Twig\TwigExtension
    arguments:
      - '@contao_bootstrap.environment'
    tags:
      - {name: 'twig.extension'}
